// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	Add(ctx context.Context, in *User, opts ...grpc.CallOption) (*AddUserResponse, error)
	UploadProfilePic(ctx context.Context, in *UploadProfilePicRequest, opts ...grpc.CallOption) (*StatusOkResponse, error)
	LoadMyMessages(ctx context.Context, in *User, opts ...grpc.CallOption) (*MyMessages, error)
	GetUserByUserId(ctx context.Context, in *GetUserByUserIdRequest, opts ...grpc.CallOption) (*User, error)
	Update(ctx context.Context, in *User, opts ...grpc.CallOption) (*StatusOkResponse, error)
	SearchUsersByUserName(ctx context.Context, in *GetUserByUserNameRequest, opts ...grpc.CallOption) (*SearchUsersByUserNameResponse, error)
	GetExistingUserNames(ctx context.Context, in *GetExistingUserNamesRequest, opts ...grpc.CallOption) (*GetExistingUserNamesResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Add(ctx context.Context, in *User, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UploadProfilePic(ctx context.Context, in *UploadProfilePicRequest, opts ...grpc.CallOption) (*StatusOkResponse, error) {
	out := new(StatusOkResponse)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/uploadProfilePic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoadMyMessages(ctx context.Context, in *User, opts ...grpc.CallOption) (*MyMessages, error) {
	out := new(MyMessages)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/loadMyMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByUserId(ctx context.Context, in *GetUserByUserIdRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/getUserByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *User, opts ...grpc.CallOption) (*StatusOkResponse, error) {
	out := new(StatusOkResponse)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchUsersByUserName(ctx context.Context, in *GetUserByUserNameRequest, opts ...grpc.CallOption) (*SearchUsersByUserNameResponse, error) {
	out := new(SearchUsersByUserNameResponse)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/searchUsersByUserName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetExistingUserNames(ctx context.Context, in *GetExistingUserNamesRequest, opts ...grpc.CallOption) (*GetExistingUserNamesResponse, error) {
	out := new(GetExistingUserNamesResponse)
	err := c.cc.Invoke(ctx, "/user_grpc.UserService/getExistingUserNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	Add(context.Context, *User) (*AddUserResponse, error)
	UploadProfilePic(context.Context, *UploadProfilePicRequest) (*StatusOkResponse, error)
	LoadMyMessages(context.Context, *User) (*MyMessages, error)
	GetUserByUserId(context.Context, *GetUserByUserIdRequest) (*User, error)
	Update(context.Context, *User) (*StatusOkResponse, error)
	SearchUsersByUserName(context.Context, *GetUserByUserNameRequest) (*SearchUsersByUserNameResponse, error)
	GetExistingUserNames(context.Context, *GetExistingUserNamesRequest) (*GetExistingUserNamesResponse, error)
	MustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Add(context.Context, *User) (*AddUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedUserServiceServer) UploadProfilePic(context.Context, *UploadProfilePicRequest) (*StatusOkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadProfilePic not implemented")
}
func (*UnimplementedUserServiceServer) LoadMyMessages(context.Context, *User) (*MyMessages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMyMessages not implemented")
}
func (*UnimplementedUserServiceServer) GetUserByUserId(context.Context, *GetUserByUserIdRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByUserId not implemented")
}
func (*UnimplementedUserServiceServer) Update(context.Context, *User) (*StatusOkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserServiceServer) SearchUsersByUserName(context.Context, *GetUserByUserNameRequest) (*SearchUsersByUserNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUsersByUserName not implemented")
}
func (*UnimplementedUserServiceServer) GetExistingUserNames(context.Context, *GetExistingUserNamesRequest) (*GetExistingUserNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExistingUserNames not implemented")
}
func (*UnimplementedUserServiceServer) MustEmbedUnimplementedUserServiceServer() {}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Add(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UploadProfilePic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadProfilePicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UploadProfilePic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/UploadProfilePic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UploadProfilePic(ctx, req.(*UploadProfilePicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoadMyMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoadMyMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/LoadMyMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoadMyMessages(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/GetUserByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByUserId(ctx, req.(*GetUserByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchUsersByUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByUserNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchUsersByUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/SearchUsersByUserName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchUsersByUserName(ctx, req.(*GetUserByUserNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetExistingUserNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExistingUserNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetExistingUserNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_grpc.UserService/GetExistingUserNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetExistingUserNames(ctx, req.(*GetExistingUserNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_grpc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _UserService_Add_Handler,
		},
		{
			MethodName: "uploadProfilePic",
			Handler:    _UserService_UploadProfilePic_Handler,
		},
		{
			MethodName: "loadMyMessages",
			Handler:    _UserService_LoadMyMessages_Handler,
		},
		{
			MethodName: "getUserByUserId",
			Handler:    _UserService_GetUserByUserId_Handler,
		},
		{
			MethodName: "update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "searchUsersByUserName",
			Handler:    _UserService_SearchUsersByUserName_Handler,
		},
		{
			MethodName: "getExistingUserNames",
			Handler:    _UserService_GetExistingUserNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user_service.proto",
}
